name: ğŸ›  Build & Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14.17.6"]
    steps:
      - name: ğŸ“ checkout
        uses: actions/checkout@v3

      - name: ğŸŸ¢ node@${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: ğŸ“¦ install packages
        run: npm ci

      - name: ğŸ›  build
        run: npm run build

      - name: ğŸš€ deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: _site
